[environment]
python-version = "3.10"
python = ".venv"

[src]
include = ["python/ghlang", "tests"]

[rules]
all = "error"
possibly-unresolved-reference = "error"
redundant-cast = "error"
unused-ignore-comment = "error"
ignore-comment-unknown-rule = "error"

[analysis]
respect-type-ignore-comments = true
allowed-unresolved-imports = ["ghlang._core"]
